name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: |
        composer install --no-interaction --prefer-dist --optimize-autoloader
        npm install

    - name: Generate Laravel key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run Dusk Tests
      run: php artisan dusk --env=testing

    - name: Install Playwright
      run: npm install playwright

    - name: Run Playwright Tests
      run: npx playwright test

    
